module BRNF

	module MutexTags
	
		MUTEX_PARENTS = [
			{
				"id"=>"58",
				"name"=>"infCons",
				"type"=>"G",
				"parent"=>"56",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:ConsCad//xs:infCons",
				"message_field"=>nil,
				"children"=>["59",
				"60",
				"61"],
				"attributes"=>[],
				"lambda" => lambda {|msg,map,xml|}
				"lambda" => lambda {|msg,|}
			},
			{
				"id"=>"64",
				"name"=>"distDFeInt",
				"type"=>"Raiz",
				"parent"=>nil, "min"=>nil, "max"=>nil, "regex"=>nil, "namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:distDFeInt",
				"message_field"=>nil, "children"=>["65",
				"66",
				"67",
				"68",
				"72"], "attributes"=>["65"],
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"81",
				"name"=>"infEvento",
				"type"=>"G",
				"parent"=>"79",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento",
				"message_field"=>nil, "children"=>["82",
				"83",
				"84",
				"86",
				"87",
				"88",
				"89",
				"90",
				"91",
				"92"], "attributes"=>["82"]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"138",
				"name"=>"dest",
				"type"=>"G",
				"parent"=>"92",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:dest",
				"message_field"=>nil, "children"=>["139",
				"140",
				"143",
				"144",
				"145",
				"146"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"158",
				"name"=>"autXML",
				"type"=>"G",
				"parent"=>"92",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:autXML",
				"message_field"=>nil, "children"=>["159"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}},
			{
				"id"=>"191",
				"name"=>"NFref",
				"type"=>"G",
				"parent"=>"166",
				"min"=>"0",
				"max"=>"500",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:ide//xs:NFref",
				"message_field"=>nil, "children"=>["192",
				"193"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"200",
				"name"=>"refNFP",
				"type"=>"CG",
				"parent"=>"191",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:ide//xs:NFref//xs:refNFP",
				"message_field"=>nil, "children"=>["201",
				"202",
				"205",
				"206",
				"207",
				"208",
				"209"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"214",
				"name"=>"emit",
				"type"=>"G",
				"parent"=>"163",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:emit",
				"message_field"=>"emissor",
				"children"=>["216",
				"217",
				"218",
				"219",
				"231",
				"232",
				"233",
				"236"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"249",
				"name"=>"dest",
				"type"=>"G",
				"parent"=>"163",
				"min"=>"0",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:dest",
				"message_field"=>"destinatario",
				"children"=>["250",
				"253",
				"254",
				"266",
				"267",
				"268",
				"269",
				"270"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"271",
				"name"=>"retirada",
				"type"=>"G",
				"parent"=>"163",
				"min"=>"0",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:retirada",
				"message_field"=>"retirada",
				"children"=>["272",
				"275",
				"276",
				"277",
				"278",
				"279",
				"280",
				"281"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"288",
				"name"=>"entrega",
				"type"=>"G",
				"parent"=>"163",
				"min"=>"0",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:entrega",
				"message_field"=>"entrega",
				"children"=>["290",
				"292",
				"293",
				"294",
				"295",
				"296",
				"297",
				"298"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"305",
				"name"=>"autXML",
				"type"=>"G",
				"parent"=>"163",
				"min"=>"0",
				"max"=>"10",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:autXML",
				"message_field"=>"autorizacoes",
				"children"=>["306"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"310",
				"name"=>"prod",
				"type"=>"G",
				"parent"=>"308",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:prod",
				"message_field"=>nil, "children"=>["311",
				"312",
				"313",
				"314",
				"315",
				"321",
				"322",
				"323",
				"324",
				"325",
				"326",
				"327",
				"328",
				"329",
				"330",
				"331",
				"332",
				"333",
				"334",
				"335",
				"336",
				"354",
				"360",
				"361",
				"362",
				"363",
				"372"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"434",
				"name"=>"imposto",
				"type"=>"G",
				"parent"=>"308",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto",
				"message_field"=>"imposto",
				"children"=>["435",
				"436",
				"764",
				"786",
				"794",
				"816",
				"824"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"437",
				"name"=>"ICMS",
				"type"=>"G",
				"parent"=>"436",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS",
				"message_field"=>"icms",
				"children"=>["472"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"707",
				"name"=>"IPI",
				"type"=>"G",
				"parent"=>"436",
				"min"=>"0",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI",
				"message_field"=>"ipi",
				"children"=>["709",
				"710",
				"711",
				"712",
				"722"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"713",
				"name"=>"IPITrib",
				"type"=>"CG",
				"parent"=>"707",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib",
				"message_field"=>nil, "children"=>["714",
				"715",
				"721"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"736",
				"name"=>"IPITrib",
				"type"=>"CG",
				"parent"=>"730",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>nil, "inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib",
				"message_field"=>nil, "children"=>["737",
				"741",
				"744"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"764",
				"name"=>"PIS",
				"type"=>"G",
				"parent"=>"434",
				"min"=>"0",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:PIS",
				"message_field"=>"pis",
				"children"=>["765"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"777",
				"name"=>"PISOutr",
				"type"=>"CG",
				"parent"=>"764",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:PIS//xs:PISOutr",
				"message_field"=>nil, "children"=>["778",
				"782",
				"785"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"786",
				"name"=>"PISST",
				"type"=>"G",
				"parent"=>"434",
				"min"=>"0",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:PISST",
				"message_field"=>nil, "children"=>["790",
				"793"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"794",
				"name"=>"COFINS",
				"type"=>"G",
				"parent"=>"434",
				"min"=>"0",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:COFINS",
				"message_field"=>"cofins",
				"children"=>["807"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"807",
				"name"=>"COFINSOutr",
				"type"=>"CG",
				"parent"=>"794",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:COFINS//xs:COFINSOutr",
				"message_field"=>nil, "children"=>["808",
				"809",
				"815"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"816",
				"name"=>"COFINSST",
				"type"=>"G",
				"parent"=>"434",
				"min"=>"0",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:COFINSST",
				"message_field"=>nil, "children"=>["820",
				"823"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"887",
				"name"=>"transporta",
				"type"=>"G",
				"parent"=>"885",
				"min"=>"0",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:transp//xs:transporta",
				"message_field"=>nil, "children"=>["889",
				"890",
				"891",
				"892",
				"893",
				"894"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"885",
				"name"=>"transp",
				"type"=>"G",
				"parent"=>"163",
				"min"=>"1",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:transp",
				"message_field"=>"transporte",
				"children"=>["886",
				"887",
				"895",
				"913",
				"915"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"911",
				"name"=>"grupo_vagao",
				"type"=>"CGO",
				"parent"=>"885",
				"min"=>"0",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:transp",
				"message_field"=>nil, "children"=>["912"], "attributes"=>[]
				"lambda" => lambda {|msg,map,xml|}
			},
			{
				"id"=>"913",
				"name"=>"grupo_balsa",
				"type"=>"CGO",
				"parent"=>"885",
				"min"=>"0",
				"max"=>"1",
				"regex"=>nil, "namespace"=>nil, "xpath_namespace"=>"http://www.portalfiscal.inf.br/nfe",
				"inferrable"=>"0",
				"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:transp",
				"message_field"=>nil, "children"=>["914"], "attributes"=>[]}
				"lambda" => lambda {|msg,map,xml|}
		]

	end

end