[
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//@versao", "count"=>6, "ids"=>["115", "123", "127", "130", "147", "153"]},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:descEvento", "count"=>6, "ids"=>["116", "124", "128", "131", "148", "154"]},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:cOrgaoAutor", "count"=>3, "ids"=>["117", "132", "155"]},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:tpAutor", "count"=>3, "ids"=>["118", "133", "156"]},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:verAplic", "count"=>3, "ids"=>["119", "134", "157"]},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:nProt", "count"=>2, "ids"=>["120", "149"]},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:xJust", "count"=>2, "ids"=>["121", "129"]},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:xCondUso", "count"=>2, "ids"=>["126", "162"]},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:CNPJProd", "count"=>2, "ids"=>["709", "732"]},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:cSelo", "count"=>2, "ids"=>["710", "733"]},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:qSelo", "count"=>2, "ids"=>["711", "734"]},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:cEnq", "count"=>2, "ids"=>["712", "735"]},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib", "count"=>2, "ids"=>["713", "736"]},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib//xs:CST", "count"=>2, "ids"=>["714", "737"]},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib//xs:vBC", "count"=>2, "ids"=>["716", "739"]},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib//xs:pIPI", "count"=>2, "ids"=>["717", "740"]},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib//xs:qUnid", "count"=>2, "ids"=>["719", "742"]},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib//xs:vUnid", "count"=>2, "ids"=>["720", "743"]},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib//xs:vIPI", "count"=>2, "ids"=>["721", "744"]},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPINT", "count"=>2, "ids"=>["722", "745"]},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPINT//xs:CST", "count"=>2, "ids"=>["723", "746"]}
]