repeated_xpaths = [
	{"xpath"=>"//xs:Signature", "ids"=>["24", "93", "995"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:SignedInfo", "ids"=>["25", "94", "996"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:SignedInfo//xs:CanonicalizationMethod", "ids"=>["26", "95", "997"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:SignedInfo//xs:CanonicalizationMethod//@Algorithm", "ids"=>["27", "96", "998"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:SignedInfo//xs:SignatureMethod", "ids"=>["28", "97", "999"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:SignedInfo//xs:SignatureMethod//@Algorithm", "ids"=>["29", "98", "1000"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:SignedInfo//xs:Reference", "ids"=>["30", "99", "1001"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:SignedInfo//xs:Reference//@URI", "ids"=>["31", "100", "1002"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:SignedInfo//xs:Reference//xs:Transforms", "ids"=>["32", "101", "1003"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:SignedInfo//xs:Reference//xs:Transforms//xs:Transform", "ids"=>["33", "36", "102", "105", "1004", "1007"], "count"=>6},
	{"xpath"=>"//xs:Signature//xs:SignedInfo//xs:Reference//xs:Transforms//xs:Transform//@Algorithm", "ids"=>["34", "37", "103", "106", "1005", "1008"], "count"=>6},
	{"xpath"=>"//xs:Signature//xs:SignedInfo//xs:Reference//xs:DigestMethod", "ids"=>["39", "108", "1010"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:SignedInfo//xs:Reference//xs:DigestMethod//@Algorithm", "ids"=>["40", "109", "1011"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:SignedInfo//xs:Reference//xs:DigestValue", "ids"=>["41", "110", "1012"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:SignatureValue", "ids"=>["42", "111", "1013"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:KeyInfo", "ids"=>["43", "112", "1014"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:KeyInfo//xs:X509Data", "ids"=>["44", "113", "1015"], "count"=>3},
	{"xpath"=>"//xs:Signature//xs:KeyInfo//xs:X509Data//xs:X509Certificate", "ids"=>["45", "114", "1016"], "count"=>3},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//@versao", "ids"=>["115", "123", "127", "130", "147", "153"], "count"=>6},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:descEvento", "ids"=>["116", "124", "128", "131", "148", "154"], "count"=>6},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:cOrgaoAutor", "ids"=>["117", "132", "155"], "count"=>3},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:tpAutor", "ids"=>["118", "133", "156"], "count"=>3},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:verAplic", "ids"=>["119", "134", "157"], "count"=>3},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:nProt", "ids"=>["120", "149"], "count"=>2},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:xJust", "ids"=>["121", "129"], "count"=>2},
	{"xpath"=>"//xs:envEvento//xs:evento//xs:infEvento//xs:detEvento//xs:xCondUso", "ids"=>["126", "162"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:ide", "ids"=>["166", "188"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:emit", "ids"=>["214", "233"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:prod", "ids"=>["310", "369", "370", "371", "372", "432"], "count"=>6},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto", "ids"=>["434", "436", "729"], "count"=>3},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMS00", "ids"=>["438", "445"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMS10", "ids"=>["448", "465", "469"], "count"=>3},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMS20", "ids"=>["472", "480", "484"], "count"=>3},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMS30", "ids"=>["487", "496", "500"], "count"=>3},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMS40", "ids"=>["503", "506"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMS51", "ids"=>["509", "520"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMS60", "ids"=>["524", "527", "532"], "count"=>3},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMS70", "ids"=>["541", "559", "563"], "count"=>3},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMS90", "ids"=>["566", "569", "575", "579", "586", "590"], "count"=>6},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMSPart", "ids"=>["593", "607"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMSSN201", "ids"=>["639", "648"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMSSN202", "ids"=>["654", "663"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMSSN500", "ids"=>["667", "670", "675", "679"], "count"=>4},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:ICMS//xs:ICMSSN900", "ids"=>["684", "687", "693", "700", "704"], "count"=>5},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:CNPJProd", "ids"=>["709", "732"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:cSelo", "ids"=>["710", "733"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:qSelo", "ids"=>["711", "734"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:cEnq", "ids"=>["712", "735"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib", "ids"=>["713", "715", "718", "736", "738", "741"], "count"=>6},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib//xs:CST", "ids"=>["714", "737"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib//xs:vBC", "ids"=>["716", "739"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib//xs:pIPI", "ids"=>["717", "740"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib//xs:qUnid", "ids"=>["719", "742"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib//xs:vUnid", "ids"=>["720", "743"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPITrib//xs:vIPI", "ids"=>["721", "744"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPINT", "ids"=>["722", "745"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:IPI//xs:IPINT//xs:CST", "ids"=>["723", "746"], "count"=>2},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:PIS//xs:PISOutr", "ids"=>["777", "779", "782"], "count"=>3},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:PISST", "ids"=>["786", "787", "790"], "count"=>3},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:COFINS//xs:COFINSOutr", "ids"=>["807", "809", "812"], "count"=>3},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:det//xs:imposto//xs:COFINSST", "ids"=>["816", "817", "820"], "count"=>3},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:transp", "ids"=>["885", "902", "911", "913"], "count"=>4},
	{"xpath"=>"//xs:enviNFe//xs:NFe//xs:infNFe//xs:infRespTec", "ids"=>["984", "989"], "count"=>2}]